dotNet_Labka1/Controllers/CalculatorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace dotNet_Labka2.Controllers
{
    public class CalculatorController : Controller
    {
        public IActionResult PlusTen(int number)
        {
            ViewData["number"] = number;
            ViewData["result"] = number + 10;

            return View();
        }
    }
}

dotNet_Labka1/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace dotNet_Labka2.Controllers
{
    public class HomeController : Controller
    {

        public IActionResult Index()
        { 
            return View();
        }

    }
}

dotNet_Labka1/Controllers/MessagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace dotNet_Labka2.Controllers
{
    public class MessagesController : Controller
    {
        public IActionResult ShowMessage(string message)
        {
            if (string.IsNullOrEmpty(message))
            {
                ViewData["Message"] = "Message is empty";
            }
            else
            {
                ViewData["Message"] = message;
            }

            return View();
        }
    }
}

dotNet_Labka1/Views/Calculator.cshtml
@{
    ViewData["Title"] = "PlusTen";
}

<h2 class="subtitle is-2">@ViewData["number"] + 10 = @ViewData["result"]</h2>

dotNet_Labka1/Views/Home/Home.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Hello from view</title>
</head>
<body>
    <h1>Hello from ☻</h1>
</body>
</html>

dotNet_Labka1/Views/Home/Index.cshtml
<section class="hero is-info is-medium is-bold">
    <div class="hero-head has-text-centered">
        <h1 class="title is-1">Hello from view with ☻</h1>
    </div
        <div class="hero-body">
            <div class="container has-text-centered">
                <h1 class="title">Lorem ipsum dolor sit amet, consectetur adipiscing elit, <br>sed eiusmod tempor incididunt ut labore et dolore magna aliqua</h1>
            </div>
        </div>
</section>

dotNet_Labka1/Views/Messages/ShowMessage.cshtml
@{
    ViewData["Title"] = "ShowMessage";
}

<h1 class="title is-1">@ViewData["Message"]</h1>

dotNet_Labka1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Hello from view</title>
    <link rel="stylesheet" href="~/css/bulma.min.css">
</head>
<body>
    <div class="container">
        <nav class="navbar" role="navigation" aria-label="main navigation">
            <div class="navbar-brand">
                <a class="navbar-item" href="/">
                    <strong class="title">My app</strong>
                </a>

                <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
                    <span aria-hidden="true"></span>
                    <span aria-hidden="true"></span>
                    <span aria-hidden="true"></span>
                </a>
            </div>

            <div id="navbarBasicExample" class="navbar-menu">
                <div class="navbar-start">
                    @Html.ActionLink("10+5", "PlusTen", "Calculator", new { number = 5 }, new { @class = "navbar-item" })
                    @Html.ActionLink("10+23", "PlusTen", "Calculator", new { number = 23 }, new { @class = "navbar-item" })
                </div>

                <div class="navbar-end">
                    <div class="navbar-item">
                        <div class="buttons">
                        </div>
                    </div>
                </div>
            </div>
        </nav>
    </div>

    <div class="container">
        @RenderBody()
    </div>
</body>
</html>